# Executor is a docker container
# cimg/base:stable -> is "CircleCI Convenience Image base" - stable verion that comprises of common tools and libraries used in envrionment development. It is feasible to define a custom dockerfile

version: 2.1 # This is the version of CircleCi being used

# Define jobs, order does not matter
jobs:
  test:
    docker: 
      - image: cimg/python:3.8.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
      - run:
          name: Run tests
          command: pytest /checkout/tests
          assert: true  # Fail workflow on test failures (optional)

  build:
    docker:
      - image: cimg/python:3.8.16 # Uses same image as the test job
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/python:3.8.16 # Uses same image as the test job
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

# Define the order of the jobs to be executed
workflows:
  example:
    jobs:
      - test
      - build:
          requires: # Note that this is serialized to not run till test is passed
            - test
      - deploy:
          requires: # Note that this is serialized to not run till test is passed
            - test
